env:
  es6: true
  node: true
  jest: true
  browser: true
extends: 'eslint:recommended'
parser: babel-eslint
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-console:
    - warn
  comma-dangle:
    - error
    - always-multiline
  no-unused-vars:
    - warn
