schema {
  query: Query
  mutation: Mutation
}

type Query {
  login: String
  series(id:ID!): Series
  episode(id:ID!): Episode
  nextEpisode(id:ID!): Episode
  unairedEpisodes(id:ID!): [Episode]
  episodes(id:ID!): [Episode]
  visitor: Visitor
  visitors: [Visitor]
  user(nickname: String!): User
  users: [User]
}

type Mutation {
  createUser(nickname: String!, mobile: String): Boolean!
}
