schema {
  query: Query
  mutation: Mutation
}

type Query {
  login: String
  series(token:String!, id:ID!): Series
  episode(token:String!, id:ID!): Episode
  nextEpisode(token:String!, id:ID!): Episode
  unairedEpisodes(token:String!, id:ID!): [Episode]
  episodes(token:String!, id:ID!): [Episode]
  visitor: Visitor
  visitors: [Visitor]
  user(nickname: String!): User
  users: [User]
}

type Mutation {
  createUser(nickname: String!, mobile: String): Boolean!
}
