schema {
  query: Query
  mutation: Mutation
}

type Query {
  login: String
  series(token:String!, id:ID!): Series
  visitor: Visitor
  visitors: [Visitor]
  user(nickname: String!): User
  users: [User]
}

type Mutation {
  createUser(nickname: String!, mobile: String): Boolean!
}
