type Series {
  id: ID
  seriesName: String
  status: String
  overview: String
  airsDayOfWeek: String
  airsTime: String
}

type Episode {
  id: ID
  episodeCode: String
  released: String
  episodeName: String
  director: String
  airedSeason: Int
  airedEpisodeNumber: Int
  firstAired: String
  overview: String
  seriesId: ID
  series: Series
  siteRating: Float
}