type Series {
  id: ID
  seriesName: String
  status: String
  overview: String
  airsDayOfWeek: String
  airsTime: String
}

type Episode {
  id: ID
  episodeName: String
  airedSeason: Int
  airedEpisodeNumber: Int
  overview: String
}